version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "09:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "09:00"
      timezone: "America/Los_Angeles"
